version: 2.1

orbs: # orbs are shareable packages of CircleCI configuration that can simplify builds.
  win: circleci/windows@5.0

jobs: # specification of jobs that can be executed
  build: # name of job
    executor:
      name: win/default
    working_directory: /tmp
    
    steps:
      - checkout: # fetch code from git repo
          path: "src"
      - run:
          name: Restore project dependencies and tools
          command: dotnet restore src/Application
      - run:
          name: Build project 
          command: dotnet build src/Application
  test: # name of job
    executor:
      name: win/default
    working_directory: /src
    steps:
      - run:
          name: "Make folder"
          command: mkdir test-results
      - run:
          name: "Running tests"
          command: dotnet test --logger "html;logfilename=test-results/testResults.html"
      - store_test_results:
          path: test-results
workflows:
  workflow-1:
    jobs:
      - build
      - test:
          requires:
            - build