version: 2.1

orbs: # orbs are shareable packages of CircleCI configuration that can simplify builds.
  win: circleci/windows@5.0

jobs: # specification of jobs that can be executed
  build: # name of job
    executor:
      name: win/default
    working_directory: /tmp
    
    steps:
      - run: mkdir -p src
      - checkout: # fetch code from git repo
          path: "src"
      - run:
          name: Restore project dependencies and tools
          command: dotnet restore src/Application
      - run:
          name: Build project 
          command: dotnet build src/Application
      - persist_to_workspace:
          root: .
          paths:
            - src/*
  test: # name of job
    executor:
      name: win/default
    working_directory: /tmp/
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./
      - run:
          name: Running Tests
          command: dotnet test src/Tests --no-build --logger "trx"
      - run:
          name: Convert Test Results
          when: always # run no matter what status it returns
          command: |
            dotnet tool install -g trx2junit
            $env:Path += '/.dotnet/tools'  
            trx2junit src/Tests/TestResults/*.trx
            dir
      - store_test_results:
         path: src/Tests/TestResults
workflows:
  workflow-1:
    jobs:
      - build
      - test:
          requires:
            - build