version: 2.1

orbs: # orbs are shareable packages of CircleCI configuration that can simplify builds.
  win: circleci/windows@5.0

jobs: # specification of jobs that can be executed
  build: # name of job
    # Default shell is powershell
    executor:
      name: win/default
    steps:
      - run: mkdir -p src
      - checkout: # fetch code from git repo
          path: "src"
      - run:
          name: Restore project dependencies and tools
          command: dotnet restore src/Application
      - run:
          name: Build project 
          command: dotnet build src/Application
      - persist_to_workspace:
          root: .
          paths:
            - src/*
  test: # name of job
    executor:
      name: win/default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./
      - run:
          name: Run tests
          command: dotnet test src/Tests --logger trx --results-directory "..\TestResults"
      - run:
          name: Install TRX 2 JUnit converter
          command: dotnet tool install -g trx2junit
          when: always

      - run:
          name: Convert TRX test results to JUnit format
          command: |
            cd $env:USERPROFILE\.dotnet\tools\
            trx2junit TestResults\*.trx
          when: always

      - store_test_results:
          path: TestResults
workflows:
  workflow-1:
    jobs:
      - build
      - test:
          requires:
            - build