version: 2.1

orbs: # orbs are shareable packages of CircleCI configuration that can simplify builds.
  win: circleci/windows@5.0

jobs: # specification of jobs that can be executed
  build: # name of job
    # Default shell is powershell
    executor:
      name: win/default
    steps:
      - run: mkdir -p src
      - checkout: # fetch code from git repo
          path: "src"
      - run:
          name: Restore Project dependencies and tools
          command: dotnet restore src\
      - run:
          name: Build Project 
          command: dotnet build src\
      - persist_to_workspace:
          root: .
          paths:
            - src/*
  test: # name of job
    executor:
      name: win/default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./
      - run:
          name: Run Tests
          command: dotnet test src\Tests --logger trx --results-directory "src\TestResults"
      - run:
          name: Convert Test Results, so CircleCI understands
          command: |
            dotnet tool install -g trx2junit
            $exePath = Join-Path $env:USERPROFILE '.dotnet\tools\trx2junit.exe'
            & $exePath src\TestResults\*.trx -output src\ConvertedTestsResults
          when: always

      - store_test_results:
          path: src\ConvertedTestsResults
workflows:
  workflow-1:
    jobs:
      - build
      - test:
          requires:
            - build